# Generated by Django 6.0 on 2026-01-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='teacher_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
